version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./wait-for-it.sh db:5432 --timeout=60 --strict -- flask db upgrade"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - flask_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./wait-for-it.sh db:5432 --timeout=60 --strict -- python run.py"
    volumes:
      - .:/app
    ports:
      - "8001:8000"  # Измененный порт для избежания конфликта
    env_file:
      - .