name: Flask CI-CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/*'
      - 'app/*'
      - 'run.py'
      - 'config.py'
      - 'tests/*'
      - 'DockerFile'
      - 'docker-compose.yml'
      - 'wait-for-it.sh'
      - '.env'
      - '.flake8'
      - 'requirements.txt'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: '123'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linters
      run: |
        flake8 .

    - name: Run tests
      run: |
        python -m unittest discover -s tests